/**
 * Full database export — the data behind the "Exportar base de datos" button.
 *
 * Walks every table declared in the data dictionary (services/dataDictionary.js),
 * reads all of its rows and serialises them, either as a multi-sheet Excel
 * workbook (one sheet per table, plus the dictionary itself) or as a single JSON
 * document usable as a logical backup.
 *
 * Two rules apply to both formats:
 *   - Columns marked `sensitive` in the dictionary (today: users.password_hash)
 *     are NEVER written out — they are replaced by "[REDACTED]".
 *   - Column order follows the dictionary, so the export is stable across runs.
 */

const XLSX = require('xlsx');
const { TABLES, ENUMS, REDACTED } = require('./dataDictionary');

// Prisma Decimal → number; Date → ISO (o YYYY-MM-DD para columnas `date`);
// Json → objeto tal cual (JSON) o texto (Excel).
function serialize(value, column, { json }) {
  if (value === null || value === undefined) return json ? null : '';
  if (value instanceof Date) {
    const iso = value.toISOString();
    return column.type === 'date' ? iso.slice(0, 10) : iso;
  }
  if (column.type.startsWith('numeric')) return Number(value);
  if (column.type === 'jsonb') return json ? value : JSON.stringify(value);
  if (typeof value === 'object') return json ? value : JSON.stringify(value);
  return value;
}

function rowToRecord(row, table, opts) {
  const out = {};
  for (const c of table.columns) {
    out[c.column] = c.sensitive ? REDACTED : serialize(row[c.field], c, opts);
  }
  return out;
}

/**
 * Lee todas las tablas. Secuencial a propósito: un dump completo no debe
 * competir por el pool de conexiones con el tráfico normal de la app.
 */
async function readAll(prisma, opts) {
  const tables = [];
  for (const table of TABLES) {
    const delegate = prisma[table.delegate];
    if (!delegate?.findMany) throw new Error(`Modelo no disponible en Prisma: ${table.delegate}`);
    const rows = await delegate.findMany();
    tables.push({ table, rows: rows.map((r) => rowToRecord(r, table, opts)), count: rows.length });
  }
  return tables;
}

// Excel limita los nombres de hoja a 31 caracteres y no admite duplicados.
function sheetName(name, used) {
  let base = name.slice(0, 31);
  let n = 2;
  while (used.has(base)) base = `${name.slice(0, 28)}_${n++}`;
  used.add(base);
  return base;
}

function aoa(header, rows) {
  return XLSX.utils.aoa_to_sheet([header, ...rows]);
}

/** Workbook completo: portada + diccionario + enums + una hoja por tabla. */
async function buildWorkbook(prisma, { generatedBy } = {}) {
  const data = await readAll(prisma, { json: false });
  const generatedAt = new Date();
  const wb = XLSX.utils.book_new();
  const used = new Set();

  // Hoja 1 — Overview: qué hay dentro y cuántas filas trae cada tabla.
  XLSX.utils.book_append_sheet(
    wb,
    aoa(
      ['Table', 'Model', 'Area', 'Rows', 'Description'],
      [
        ...data.map(({ table, count }) => [table.table, table.model, table.group, count, table.description]),
        [],
        ['TOTAL', '', '', data.reduce((s, d) => s + d.count, 0), ''],
        [],
        ['Generated at', generatedAt.toISOString()],
        ['Generated by', generatedBy || ''],
        ['Note', `Columns marked as sensitive are exported as "${REDACTED}" (password hashes never leave the server).`],
      ]
    ),
    sheetName('Overview', used)
  );

  // Hoja 2 — el diccionario, para que el archivo se explique solo.
  XLSX.utils.book_append_sheet(
    wb,
    aoa(
      ['Table', 'Column', 'Prisma field', 'Type', 'Nullable', 'Key', 'Description'],
      TABLES.flatMap((t) =>
        t.columns.map((c) => [t.table, c.column, c.field, c.type, c.nullable ? 'YES' : 'NO', c.key || '', c.description])
      )
    ),
    sheetName('Data Dictionary', used)
  );

  // Hoja 3 — enums.
  XLSX.utils.book_append_sheet(
    wb,
    aoa(
      ['Enum', 'Value', 'Meaning'],
      ENUMS.flatMap((e) => e.values.map(([v, d]) => [e.name, v, d]))
    ),
    sheetName('Enums', used)
  );

  // Una hoja por tabla, con las columnas en el orden del diccionario.
  for (const { table, rows } of data) {
    const header = table.columns.map((c) => c.column);
    XLSX.utils.book_append_sheet(
      wb,
      aoa(header, rows.map((r) => header.map((h) => r[h]))),
      sheetName(table.table, used)
    );
  }

  return {
    buffer: XLSX.write(wb, { type: 'buffer', bookType: 'xlsx' }),
    generatedAt,
    totalRows: data.reduce((s, d) => s + d.count, 0),
    tables: data.map(({ table, count }) => ({ table: table.table, rows: count })),
  };
}

/** Volcado JSON: mismo contenido, pensado como respaldo lógico legible por máquina. */
async function buildJson(prisma, { generatedBy } = {}) {
  const data = await readAll(prisma, { json: true });
  const generatedAt = new Date();
  return {
    meta: {
      generatedAt: generatedAt.toISOString(),
      generatedBy: generatedBy || null,
      redacted: REDACTED,
      note: 'Sensitive columns (password hashes) are redacted. Column names are the physical SQL names.',
      tables: data.map(({ table, count }) => ({ table: table.table, model: table.model, rows: count })),
      totalRows: data.reduce((s, d) => s + d.count, 0),
    },
    data: Object.fromEntries(data.map(({ table, rows }) => [table.table, rows])),
  };
}

module.exports = { buildWorkbook, buildJson, readAll, serialize };
